### ISSUE TITLE
Failiure to attribute

### ISSUE THREAD

**Issue by joker314** [newawe/Sandbox#6]
We appear to be piggy backing our code executer over another website. This is a bit naughty?

**Comment by RonSkons** [comment]
I will try to contact the site.

**Comment by RonSkons** [comment]
It seems to be open source though.  https://github.com/ren85/rextester_win

**Comment by RonSkons** [comment]
WAIT! It has an API. I was using it without knowing. Read the API section in http://rextester.com/main

**Comment by joker314** [comment]
We should still give a small notice no our page, it is really nice of them to haven API

**Comment by RonSkons** [comment]
Yup. I will add a link.

**Comment by RonSkons** [comment]
Working on some general editor updates. Will add that with them.

**Comment by RonSkons** [comment]
Done. Check it out when you have time.

**Comment by joker314** [comment]
kk

**Comment by RonSkons** [comment]
Maybe close the issue? 😝
